

#pragma once

#ifndef GO_MOC_H
#define GO_MOC_H

#include <stdint.h>

#ifdef __cplusplus
class Ui_Dialog9733cb;
void Ui_Dialog9733cb_Ui_Dialog9733cb_QRegisterMetaTypes();
class Ui_SysTray9733cb;
void Ui_SysTray9733cb_Ui_SysTray9733cb_QRegisterMetaTypes();
class AppDoingList9733cb;
void AppDoingList9733cb_AppDoingList9733cb_QRegisterMetaTypes();
class DoingList9733cb;
void DoingList9733cb_DoingList9733cb_QRegisterMetaTypes();
extern "C" {
#endif

struct Moc_PackedString { char* data; long long len; };
struct Moc_PackedList { void* data; long long len; };
int DoingList9733cb_DoingList9733cb_QRegisterMetaType();
int DoingList9733cb_DoingList9733cb_QRegisterMetaType2(char* typeName);
int DoingList9733cb_DoingList9733cb_QmlRegisterType();
int DoingList9733cb_DoingList9733cb_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* DoingList9733cb___findItems_atList(void* ptr, int i);
void DoingList9733cb___findItems_setList(void* ptr, void* i);
void* DoingList9733cb___findItems_newList(void* ptr);
void* DoingList9733cb___items_atList(void* ptr, int i);
void DoingList9733cb___items_setList(void* ptr, void* i);
void* DoingList9733cb___items_newList(void* ptr);
void* DoingList9733cb___selectedItems_atList(void* ptr, int i);
void DoingList9733cb___selectedItems_setList(void* ptr, void* i);
void* DoingList9733cb___selectedItems_newList(void* ptr);
void* DoingList9733cb___mimeData_items_atList(void* ptr, int i);
void DoingList9733cb___mimeData_items_setList(void* ptr, void* i);
void* DoingList9733cb___mimeData_items_newList(void* ptr);
int DoingList9733cb___dataChanged_roles_atList(void* ptr, int i);
void DoingList9733cb___dataChanged_roles_setList(void* ptr, int i);
void* DoingList9733cb___dataChanged_roles_newList(void* ptr);
void* DoingList9733cb___indexesMoved_indexes_atList(void* ptr, int i);
void DoingList9733cb___indexesMoved_indexes_setList(void* ptr, void* i);
void* DoingList9733cb___indexesMoved_indexes_newList(void* ptr);
void* DoingList9733cb___selectedIndexes_atList(void* ptr, int i);
void DoingList9733cb___selectedIndexes_setList(void* ptr, void* i);
void* DoingList9733cb___selectedIndexes_newList(void* ptr);
void* DoingList9733cb___scrollBarWidgets_atList(void* ptr, int i);
void DoingList9733cb___scrollBarWidgets_setList(void* ptr, void* i);
void* DoingList9733cb___scrollBarWidgets_newList(void* ptr);
void* DoingList9733cb___addActions_actions_atList(void* ptr, int i);
void DoingList9733cb___addActions_actions_setList(void* ptr, void* i);
void* DoingList9733cb___addActions_actions_newList(void* ptr);
void* DoingList9733cb___insertActions_actions_atList(void* ptr, int i);
void DoingList9733cb___insertActions_actions_setList(void* ptr, void* i);
void* DoingList9733cb___insertActions_actions_newList(void* ptr);
void* DoingList9733cb___actions_atList(void* ptr, int i);
void DoingList9733cb___actions_setList(void* ptr, void* i);
void* DoingList9733cb___actions_newList(void* ptr);
void* DoingList9733cb___dynamicPropertyNames_atList(void* ptr, int i);
void DoingList9733cb___dynamicPropertyNames_setList(void* ptr, void* i);
void* DoingList9733cb___dynamicPropertyNames_newList(void* ptr);
void* DoingList9733cb___findChildren_atList2(void* ptr, int i);
void DoingList9733cb___findChildren_setList2(void* ptr, void* i);
void* DoingList9733cb___findChildren_newList2(void* ptr);
void* DoingList9733cb___findChildren_atList3(void* ptr, int i);
void DoingList9733cb___findChildren_setList3(void* ptr, void* i);
void* DoingList9733cb___findChildren_newList3(void* ptr);
void* DoingList9733cb___findChildren_atList(void* ptr, int i);
void DoingList9733cb___findChildren_setList(void* ptr, void* i);
void* DoingList9733cb___findChildren_newList(void* ptr);
void* DoingList9733cb___children_atList(void* ptr, int i);
void DoingList9733cb___children_setList(void* ptr, void* i);
void* DoingList9733cb___children_newList(void* ptr);
void* DoingList9733cb_NewDoingList(void* parent);
void DoingList9733cb_DestroyDoingList(void* ptr);
void DoingList9733cb_DestroyDoingListDefault(void* ptr);
char DoingList9733cb_DropMimeDataDefault(void* ptr, int index, void* data, long long action);
char DoingList9733cb_EventDefault(void* ptr, void* e);
void DoingList9733cb_ClearDefault(void* ptr);
void DoingList9733cb_DropEventDefault(void* ptr, void* event);
void DoingList9733cb_ScrollToItemDefault(void* ptr, void* item, long long hint);
void DoingList9733cb_SetSelectionModelDefault(void* ptr, void* selectionModel);
void* DoingList9733cb_MimeDataDefault(void* ptr, void* items);
struct Moc_PackedString DoingList9733cb_MimeTypesDefault(void* ptr);
long long DoingList9733cb_SupportedDropActionsDefault(void* ptr);
;
void* DoingList9733cb_MoveCursorDefault(void* ptr, long long cursorAction, long long modifiers);
void DoingList9733cb_CurrentChangedDefault(void* ptr, void* current, void* previous);
void DoingList9733cb_DataChangedDefault(void* ptr, void* topLeft, void* bottomRight, void* roles);
void DoingList9733cb_DragLeaveEventDefault(void* ptr, void* e);
void DoingList9733cb_DragMoveEventDefault(void* ptr, void* e);
void DoingList9733cb_MouseMoveEventDefault(void* ptr, void* e);
void DoingList9733cb_MouseReleaseEventDefault(void* ptr, void* e);
void DoingList9733cb_PaintEventDefault(void* ptr, void* e);
void DoingList9733cb_ResizeEventDefault(void* ptr, void* e);
void DoingList9733cb_RowsAboutToBeRemovedDefault(void* ptr, void* parent, int start, int end);
void DoingList9733cb_RowsInsertedDefault(void* ptr, void* parent, int start, int end);
void DoingList9733cb_ScrollToDefault(void* ptr, void* index, long long hint);
void DoingList9733cb_SelectionChangedDefault(void* ptr, void* selected, void* deselected);
void DoingList9733cb_SetSelectionDefault(void* ptr, void* rect, long long command);
void DoingList9733cb_StartDragDefault(void* ptr, long long supportedActions);
void DoingList9733cb_TimerEventDefault(void* ptr, void* e);
void DoingList9733cb_UpdateGeometriesDefault(void* ptr);
void DoingList9733cb_WheelEventDefault(void* ptr, void* e);
void* DoingList9733cb_IndexAtDefault(void* ptr, void* p);
struct Moc_PackedList DoingList9733cb_SelectedIndexesDefault(void* ptr);
void* DoingList9733cb_VisualRectDefault(void* ptr, void* index);
void* DoingList9733cb_VisualRegionForSelectionDefault(void* ptr, void* selection);
void* DoingList9733cb_ViewportSizeHintDefault(void* ptr);
void* DoingList9733cb_ViewOptionsDefault(void* ptr);
char DoingList9733cb_IsIndexHiddenDefault(void* ptr, void* index);
int DoingList9733cb_HorizontalOffsetDefault(void* ptr);
int DoingList9733cb_VerticalOffsetDefault(void* ptr);
char DoingList9733cb_Edit2Default(void* ptr, void* index, long long trigger, void* event);
char DoingList9733cb_EventFilterDefault(void* ptr, void* object, void* event);
char DoingList9733cb_FocusNextPrevChildDefault(void* ptr, char next);
char DoingList9733cb_ViewportEventDefault(void* ptr, void* event);
void DoingList9733cb_ClearSelectionDefault(void* ptr);
void DoingList9733cb_CloseEditorDefault(void* ptr, void* editor, long long hint);
void DoingList9733cb_CommitDataDefault(void* ptr, void* editor);
void DoingList9733cb_DragEnterEventDefault(void* ptr, void* event);
void DoingList9733cb_EditDefault(void* ptr, void* index);
void DoingList9733cb_EditorDestroyedDefault(void* ptr, void* editor);
void DoingList9733cb_FocusInEventDefault(void* ptr, void* event);
void DoingList9733cb_FocusOutEventDefault(void* ptr, void* event);
void DoingList9733cb_InputMethodEventDefault(void* ptr, void* event);
void DoingList9733cb_KeyPressEventDefault(void* ptr, void* event);
void DoingList9733cb_KeyboardSearchDefault(void* ptr, struct Moc_PackedString search);
void DoingList9733cb_MouseDoubleClickEventDefault(void* ptr, void* event);
void DoingList9733cb_MousePressEventDefault(void* ptr, void* event);
void DoingList9733cb_ResetDefault(void* ptr);
void DoingList9733cb_ScrollToBottomDefault(void* ptr);
void DoingList9733cb_ScrollToTopDefault(void* ptr);
void DoingList9733cb_SelectAllDefault(void* ptr);
void DoingList9733cb_SetCurrentIndexDefault(void* ptr, void* index);
void DoingList9733cb_SetModelDefault(void* ptr, void* model);
void DoingList9733cb_SetRootIndexDefault(void* ptr, void* index);
void DoingList9733cb_UpdateDefault(void* ptr, void* index);
long long DoingList9733cb_SelectionCommandDefault(void* ptr, void* index, void* event);
void* DoingList9733cb_InputMethodQueryDefault(void* ptr, long long query);
int DoingList9733cb_SizeHintForColumnDefault(void* ptr, int column);
int DoingList9733cb_SizeHintForRowDefault(void* ptr, int row);
void DoingList9733cb_ContextMenuEventDefault(void* ptr, void* e);
void DoingList9733cb_ScrollContentsByDefault(void* ptr, int dx, int dy);
void DoingList9733cb_SetupViewportDefault(void* ptr, void* viewport);
void* DoingList9733cb_MinimumSizeHintDefault(void* ptr);
void* DoingList9733cb_SizeHintDefault(void* ptr);
void DoingList9733cb_ChangeEventDefault(void* ptr, void* ev);
char DoingList9733cb_CloseDefault(void* ptr);
void DoingList9733cb_ActionEventDefault(void* ptr, void* event);
void DoingList9733cb_CloseEventDefault(void* ptr, void* event);
void DoingList9733cb_EnterEventDefault(void* ptr, void* event);
void DoingList9733cb_HideDefault(void* ptr);
void DoingList9733cb_HideEventDefault(void* ptr, void* event);
void DoingList9733cb_KeyReleaseEventDefault(void* ptr, void* event);
void DoingList9733cb_LeaveEventDefault(void* ptr, void* event);
void DoingList9733cb_LowerDefault(void* ptr);
void DoingList9733cb_MoveEventDefault(void* ptr, void* event);
void DoingList9733cb_RaiseDefault(void* ptr);
void DoingList9733cb_RepaintDefault(void* ptr);
void DoingList9733cb_SetDisabledDefault(void* ptr, char disable);
void DoingList9733cb_SetEnabledDefault(void* ptr, char vbo);
void DoingList9733cb_SetFocus2Default(void* ptr);
void DoingList9733cb_SetHiddenDefault(void* ptr, char hidden);
void DoingList9733cb_SetStyleSheetDefault(void* ptr, struct Moc_PackedString styleSheet);
void DoingList9733cb_SetVisibleDefault(void* ptr, char visible);
void DoingList9733cb_SetWindowModifiedDefault(void* ptr, char vbo);
void DoingList9733cb_SetWindowTitleDefault(void* ptr, struct Moc_PackedString vqs);
void DoingList9733cb_ShowDefault(void* ptr);
void DoingList9733cb_ShowEventDefault(void* ptr, void* event);
void DoingList9733cb_ShowFullScreenDefault(void* ptr);
void DoingList9733cb_ShowMaximizedDefault(void* ptr);
void DoingList9733cb_ShowMinimizedDefault(void* ptr);
void DoingList9733cb_ShowNormalDefault(void* ptr);
void DoingList9733cb_TabletEventDefault(void* ptr, void* event);
void DoingList9733cb_UpdateMicroFocusDefault(void* ptr);
void* DoingList9733cb_PaintEngineDefault(void* ptr);
char DoingList9733cb_HasHeightForWidthDefault(void* ptr);
int DoingList9733cb_HeightForWidthDefault(void* ptr, int w);
int DoingList9733cb_MetricDefault(void* ptr, long long m);
void DoingList9733cb_InitPainterDefault(void* ptr, void* painter);
void DoingList9733cb_ChildEventDefault(void* ptr, void* event);
void DoingList9733cb_ConnectNotifyDefault(void* ptr, void* sign);
void DoingList9733cb_CustomEventDefault(void* ptr, void* event);
void DoingList9733cb_DeleteLaterDefault(void* ptr);
void DoingList9733cb_DisconnectNotifyDefault(void* ptr, void* sign);
void Ui_Dialog9733cb_ActivateEvent(void* ptr, void* v0, void* v1);
int Ui_Dialog9733cb_Ui_Dialog9733cb_QRegisterMetaType();
int Ui_Dialog9733cb_Ui_Dialog9733cb_QRegisterMetaType2(char* typeName);
int Ui_Dialog9733cb_Ui_Dialog9733cb_QmlRegisterType();
int Ui_Dialog9733cb_Ui_Dialog9733cb_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* Ui_Dialog9733cb___dynamicPropertyNames_atList(void* ptr, int i);
void Ui_Dialog9733cb___dynamicPropertyNames_setList(void* ptr, void* i);
void* Ui_Dialog9733cb___dynamicPropertyNames_newList(void* ptr);
void* Ui_Dialog9733cb___findChildren_atList2(void* ptr, int i);
void Ui_Dialog9733cb___findChildren_setList2(void* ptr, void* i);
void* Ui_Dialog9733cb___findChildren_newList2(void* ptr);
void* Ui_Dialog9733cb___findChildren_atList3(void* ptr, int i);
void Ui_Dialog9733cb___findChildren_setList3(void* ptr, void* i);
void* Ui_Dialog9733cb___findChildren_newList3(void* ptr);
void* Ui_Dialog9733cb___findChildren_atList(void* ptr, int i);
void Ui_Dialog9733cb___findChildren_setList(void* ptr, void* i);
void* Ui_Dialog9733cb___findChildren_newList(void* ptr);
void* Ui_Dialog9733cb___children_atList(void* ptr, int i);
void Ui_Dialog9733cb___children_setList(void* ptr, void* i);
void* Ui_Dialog9733cb___children_newList(void* ptr);
void* Ui_Dialog9733cb_NewUi_Dialog(void* parent);
void Ui_Dialog9733cb_DestroyUi_Dialog(void* ptr);
void Ui_Dialog9733cb_DestroyUi_DialogDefault(void* ptr);
char Ui_Dialog9733cb_EventDefault(void* ptr, void* e);
char Ui_Dialog9733cb_EventFilterDefault(void* ptr, void* watched, void* event);
void Ui_Dialog9733cb_ChildEventDefault(void* ptr, void* event);
void Ui_Dialog9733cb_ConnectNotifyDefault(void* ptr, void* sign);
void Ui_Dialog9733cb_CustomEventDefault(void* ptr, void* event);
void Ui_Dialog9733cb_DeleteLaterDefault(void* ptr);
void Ui_Dialog9733cb_DisconnectNotifyDefault(void* ptr, void* sign);
void Ui_Dialog9733cb_TimerEventDefault(void* ptr, void* event);
;
int Ui_SysTray9733cb_Ui_SysTray9733cb_QRegisterMetaType();
int Ui_SysTray9733cb_Ui_SysTray9733cb_QRegisterMetaType2(char* typeName);
int Ui_SysTray9733cb_Ui_SysTray9733cb_QmlRegisterType();
int Ui_SysTray9733cb_Ui_SysTray9733cb_QmlRegisterType2(char* uri, int versionMajor, int versionMinor, char* qmlName);
void* Ui_SysTray9733cb___dynamicPropertyNames_atList(void* ptr, int i);
void Ui_SysTray9733cb___dynamicPropertyNames_setList(void* ptr, void* i);
void* Ui_SysTray9733cb___dynamicPropertyNames_newList(void* ptr);
void* Ui_SysTray9733cb___findChildren_atList2(void* ptr, int i);
void Ui_SysTray9733cb___findChildren_setList2(void* ptr, void* i);
void* Ui_SysTray9733cb___findChildren_newList2(void* ptr);
void* Ui_SysTray9733cb___findChildren_atList3(void* ptr, int i);
void Ui_SysTray9733cb___findChildren_setList3(void* ptr, void* i);
void* Ui_SysTray9733cb___findChildren_newList3(void* ptr);
void* Ui_SysTray9733cb___findChildren_atList(void* ptr, int i);
void Ui_SysTray9733cb___findChildren_setList(void* ptr, void* i);
void* Ui_SysTray9733cb___findChildren_newList(void* ptr);
void* Ui_SysTray9733cb___children_atList(void* ptr, int i);
void Ui_SysTray9733cb___children_setList(void* ptr, void* i);
void* Ui_SysTray9733cb___children_newList(void* ptr);
void* Ui_SysTray9733cb_NewUi_SysTray(void* parent);
void Ui_SysTray9733cb_DestroyUi_SysTray(void* ptr);
void Ui_SysTray9733cb_DestroyUi_SysTrayDefault(void* ptr);
char Ui_SysTray9733cb_EventDefault(void* ptr, void* e);
char Ui_SysTray9733cb_EventFilterDefault(void* ptr, void* watched, void* event);
void Ui_SysTray9733cb_ChildEventDefault(void* ptr, void* event);
void Ui_SysTray9733cb_ConnectNotifyDefault(void* ptr, void* sign);
void Ui_SysTray9733cb_CustomEventDefault(void* ptr, void* event);
void Ui_SysTray9733cb_DeleteLaterDefault(void* ptr);
void Ui_SysTray9733cb_DisconnectNotifyDefault(void* ptr, void* sign);
void Ui_SysTray9733cb_TimerEventDefault(void* ptr, void* event);
;
void AppDoingList9733cb_ConnectQuitApp(void* ptr);
void AppDoingList9733cb_DisconnectQuitApp(void* ptr);
void AppDoingList9733cb_QuitApp(void* ptr);
void AppDoingList9733cb_ConnectActivateApp(void* ptr);
void AppDoingList9733cb_DisconnectActivateApp(void* ptr);
void AppDoingList9733cb_ActivateApp(void* ptr);
int AppDoingList9733cb_AppDoingList9733cb_QRegisterMetaType();
int AppDoingList9733cb_AppDoingList9733cb_QRegisterMetaType2(char* typeName);
void* AppDoingList9733cb___allWidgets_atList(void* ptr, int i);
void AppDoingList9733cb___allWidgets_setList(void* ptr, void* i);
void* AppDoingList9733cb___allWidgets_newList(void* ptr);
void* AppDoingList9733cb___topLevelWidgets_atList(void* ptr, int i);
void AppDoingList9733cb___topLevelWidgets_setList(void* ptr, void* i);
void* AppDoingList9733cb___topLevelWidgets_newList(void* ptr);
void* AppDoingList9733cb___screens_atList(void* ptr, int i);
void AppDoingList9733cb___screens_setList(void* ptr, void* i);
void* AppDoingList9733cb___screens_newList(void* ptr);
void* AppDoingList9733cb___dynamicPropertyNames_atList(void* ptr, int i);
void AppDoingList9733cb___dynamicPropertyNames_setList(void* ptr, void* i);
void* AppDoingList9733cb___dynamicPropertyNames_newList(void* ptr);
void* AppDoingList9733cb___findChildren_atList2(void* ptr, int i);
void AppDoingList9733cb___findChildren_setList2(void* ptr, void* i);
void* AppDoingList9733cb___findChildren_newList2(void* ptr);
void* AppDoingList9733cb___findChildren_atList3(void* ptr, int i);
void AppDoingList9733cb___findChildren_setList3(void* ptr, void* i);
void* AppDoingList9733cb___findChildren_newList3(void* ptr);
void* AppDoingList9733cb___findChildren_atList(void* ptr, int i);
void AppDoingList9733cb___findChildren_setList(void* ptr, void* i);
void* AppDoingList9733cb___findChildren_newList(void* ptr);
void* AppDoingList9733cb___children_atList(void* ptr, int i);
void AppDoingList9733cb___children_setList(void* ptr, void* i);
void* AppDoingList9733cb___children_newList(void* ptr);
void* AppDoingList9733cb_NewAppDoingList(int argc, char* argv);
void AppDoingList9733cb_DestroyAppDoingList(void* ptr);
void AppDoingList9733cb_DestroyAppDoingListDefault(void* ptr);
char AppDoingList9733cb_EventDefault(void* ptr, void* e);
void AppDoingList9733cb_AboutQtDefault(void* ptr);
void AppDoingList9733cb_CloseAllWindowsDefault(void* ptr);
void AppDoingList9733cb_SetAutoSipEnabledDefault(void* ptr, char enabled);
void AppDoingList9733cb_SetStyleSheetDefault(void* ptr, struct Moc_PackedString sheet);
char AppDoingList9733cb_AutoSipEnabledDefault(void* ptr);
;
void AppDoingList9733cb_QuitDefault(void* ptr);
char AppDoingList9733cb_EventFilterDefault(void* ptr, void* watched, void* event);
void AppDoingList9733cb_ChildEventDefault(void* ptr, void* event);
void AppDoingList9733cb_ConnectNotifyDefault(void* ptr, void* sign);
void AppDoingList9733cb_CustomEventDefault(void* ptr, void* event);
void AppDoingList9733cb_DeleteLaterDefault(void* ptr);
void AppDoingList9733cb_DisconnectNotifyDefault(void* ptr, void* sign);
void AppDoingList9733cb_TimerEventDefault(void* ptr, void* event);

#ifdef __cplusplus
}
#endif

#endif